# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in rspec-multicore.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"

gem "rspec", "~> 3.13"
gem "rspec-core", ENV.fetch("RSPEC_CORE_VERSION", "~> 3.13")

gem "rubocop", "~> 1.21"
gem "rubocop-rspec", "~> 3.0"

gem "byebug"
