# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec) do |task|
  task.exclude_pattern = "spec/fixtures/**/*_spec.rb"
end

require "rubocop/rake_task"

RuboCop::RakeTask.new

task default: :spec
