# frozen_string_literal: true

source "https://rubygems.org"

rails_version = ENV.fetch("RAILS_VERSION", "~> 8.0.0")

gem "activerecord", rails_version
gem "database_cleaner-active_record", "2.2.2"
gem "factory_bot_rails", "6.5.1"
gem "railties", rails_version
gem "rspec", "~> 3.13"
gem "rspec_junit_formatter", "0.6.0"
gem "rspec-multicore", path: "../../rspec-multicore"
gem "rspec-multicore-rails", path: "../../rspec-multicore-rails"
gem "simplecov", "1.0.3"
gem "sqlite3", ">= 2.0"
gem "vcr", "6.4.0"
gem "webmock", "3.26.2"
